# Generated by Django 2.1.3 on 2018-11-23 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=30)),
                ('receiver', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 11, 23, 12, 30, 0, 26027))),
            ],
        ),
    ]
