# Generated by Django 2.1.3 on 2018-11-23 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20181123_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 22, 6, 45, 265088)),
        ),
    ]
